name: buttons_panel
description: A buttons panel package for Flutter. It's like a group of buttons in a line.
version: 0.0.1
homepage: https://github.com/Itz-Shubham/buttons_panel
repository: https://github.com/Itz-Shubham/buttons_panel

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
